site_name: cloudwatcher
theme:
  name: material
  palette:
    - scheme: default
      primary: black
      toggle:
        primary: black
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: material/github
repo_url: https://github.com/niaid/cloudwatcher
repo_name: niaid/cloudwatcher
edit_uri: edit/main/docs/
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
nav:
  - Overview: README.md
  - Installation & Setup:
      - Installation: installation.md
      - EC2 intance setup: EC2_instance_setup.md
      - AWS credentials: login_credentials.md
  - Usage & Features:
      - Usage: usage.md
      - Features: features.md
      - Presets: presets.md
  - Python API:
      - API documentation: API_documentation.md
      - API usage: API_usage.md
  - Development:
      - Docs development: docs_development.md
  - Release notes: changelog.md
